# Generated by Django 5.1 on 2024-08-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('process', models.TextField()),
                ('ingredients', models.TextField()),
                ('picture', models.ImageField(upload_to='recipes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
