# Generated by Django 5.1 on 2024-10-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes_delete_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
